### ISSUE TITLE
Is it possible to running this tool on Linux?

### ISSUE THREAD

**Issue by diy10264** [cognidox/OfficeToPDF#43]
Could replace .NET Framework to [momo](https://github.com/mono/mono) ? 

Thanks.

**Comment by vittala** [comment]
Hi

OfficeToPDF can't run on Linux because it needs a working version of Office too. Without Office and its interop libraries, the Office documents can't be rendered.

On Linux, I'd suggest looking at LibreOffice (https://www.libreoffice.org/) and making use of its --convert-to command line option - see https://gist.github.com/diogo-almeida/9339203

Regards
Vittal
